import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import importX from 'eslint-plugin-import-x';
import reactHooks from 'eslint-plugin-react-hooks';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      // Generated by `wrangler types`.
      'src/server/worker-env.d.ts',
      'worker-configuration.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx,js,mjs}'],
    plugins: { 'import-x': importX, 'react-hooks': reactHooks },
    settings: {
      'import-x/resolver-next': [
        createTypeScriptImportResolver({ project: './tsconfig.json' }),
      ],
    },
    rules: {
      // TypeScript resolves every identifier already, and does it correctly for types, `declare`,
      // and the Worker/DOM lib globals. Leaving this on means re-declaring hundreds of ambient
      // globals in ESLint just to get a worse version of a check `npm run typecheck` already runs.
      'no-undef': 'off',

      // The base rule cannot see TypeScript's type-only positions; the TS one can.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['error', {
        // `catch {}` is the preferred form, but an unused binding is not worth an error.
        caughtErrors: 'none',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      }],

      // `import-x/no-duplicates` and NOT the core `no-duplicate-imports`: the core rule is type-blind
      // and flags the deliberate `import { Hono }` + `import type { Context }` split as a duplicate.
      'import-x/no-duplicates': 'error',
      'import-x/no-self-import': 'error',
      'import-x/no-cycle': 'error',

      // 400 lines, counting neither blanks nor comments, so adding an explanation never pushes a file
      // over. One file carries an explicit override below, for a stated reason -- a second should
      // be a split, not a second override.
      'max-lines': ['error', { max: 400, skipBlankLines: true, skipComments: true }],

      // An error, not a warning: the three places whose dependency array is deliberately narrower
      // than their closure now carry a line-level disable stating why. A new violation should fail.
      'react-hooks/exhaustive-deps': 'error',

      // Fires on the finding-title normalizer, which strips emoji and variation selectors from model
      // output. Those combining characters are the point of it, and its behaviour is pinned by tests.
      'no-misleading-character-class': 'off',

      // `any` is used deliberately at the provider and DB boundaries, where the shape is genuinely
      // unknown until it is parsed. Turning this on would mean ~100 suppressions, not better types.
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    files: ['src/client/**/*.{ts,tsx}'],
    rules: {
      'react-hooks/rules-of-hooks': 'error',
    },
  },

  {
    // These specifiers are intercepted BY STRING in test mocks (`vi.mock('@server/db/jobs', ...)`).
    // Each one is free to split into sibling files internally, but every other module must keep
    // importing the barrel path -- importing a sibling directly bypasses whichever spec mocks the
    // barrel, and the test keeps passing while asserting nothing.
    //
    // Every group MUST list the `@alias/...` form, not just `**/dir/...`. Under the tsconfig paths
    // (`@shared/*` -> src/shared/*) the specifier a consumer actually writes is `@shared/schema-claims`,
    // whose segments are ["@shared", "schema-claims"] -- there is no literal `shared` segment for
    // `**/shared/` to match, so that pattern silently matched nothing at all. `@server/*` groups
    // happen to work because `db`/`core`/`review` survive as real segments, but spell both forms out
    // rather than relying on that. Probe any new pattern with:
    //   echo "import '<spec>';" | npx eslint --stdin --stdin-filename src/server/probe.ts
    files: ['src/**/*.{ts,tsx}', 'test/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [
          { group: ['**/db/jobs-*', '@server/db/jobs-*'], message: 'Import from @server/db/jobs, not a sibling. Eight specs vi.mock that specifier; a direct sibling import silently bypasses the mock.' },
          { group: ['**/db/file-reviews-*', '@server/db/file-reviews-*'], message: 'Import from @server/db/file-reviews, not a sibling. (No spec mocks this one today; the rule keeps the barrel the single entry point.)' },
          { group: ['**/services/model-review-*', '**/services/model-rate-limits', '**/services/model-chain-runner', '**/services/model-support', '@server/services/model-*'], message: 'Import from @server/services/model, not a sibling. Four specs vi.mock that specifier.' },
          { group: ['**/core/github/http', '**/core/github/app-auth', '**/core/github/types', '**/core/github/diff-fetch', '**/core/github/review-post', '**/core/github/labels', '@server/core/github/http', '@server/core/github/app-auth', '@server/core/github/types', '@server/core/github/diff-fetch', '@server/core/github/review-post', '@server/core/github/labels'], message: 'Import from @server/core/github, not a sibling. One spec vi.mocks that specifier. (core/github/oauth is deliberately NOT listed: it is the dashboard OAuth flow, not part of the GitHubClient barrel, and routes/auth.ts imports it directly.)' },
          // Covers every sibling in the family, including the three the barrel re-exports publicly
          // (budget, diff-cache, request) which were previously unprotected.
          { group: ['**/core/review/*', '@server/core/review/*'], message: 'Import from @server/core/review, not a sibling. One spec vi.mocks that specifier and workflows/review.ts imports only runReviewJob from it.' },
          { group: ['**/core/model-output/*', '@server/core/model-output/*'], message: 'Import from @server/core/model-output, not a sibling.' },
          { group: ['**/core/diff/position', '@server/core/diff/position'], message: 'Import from @server/core/diff, not a sibling.' },
          { group: ['**/schema-claims', '**/schema-repo-config', '**/schema-enums', '@codra/schema/schema-claims', '@codra/schema/schema-repo-config', '@codra/schema/schema-enums'], message: 'Import from @codra/schema, not a sibling. (@codra/schema/review-limits is exempt: the client imports it directly to keep zod out of the browser bundle.)' },
        ],
      }],
    },
  },
  {
    // The one file still over the limit, for a stated reason. Known work, not a permanent
    // carve-out -- delete the entry rather than raising `max` when it is split.
    //
    // test/api/auth.spec.ts (422): the review-settings suites here read-modify-write the same
    //   singleton `global_settings` row set and race across files once `fileParallelism` is on. See
    //   the DO-NOT-SPLIT header on the file itself.
    files: ['test/api/auth.spec.ts'],
    rules: {
      'max-lines': 'off',
    },
  },

  {
    // The barrel files themselves are the one place allowed to import their own siblings.
    files: [
      'src/server/db/jobs.ts',
      'src/server/db/file-reviews.ts',
      'src/server/services/model.ts',
      'src/server/core/github/index.ts',
      'src/server/core/review/index.ts',
      'src/server/core/diff/index.ts',
      'src/server/core/model-output/index.ts',
      'packages/schema/src/schema.ts',
    ],
    rules: {
      'no-restricted-imports': 'off',
    },
  },

  {
    // Plain-JS scripts are not covered by tsconfig, so they need their globals declared.
    files: ['scripts/**/*.{js,mjs}'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        __dirname: 'readonly',
      },
    },
  },

  {
    files: ['packages/**/*.{ts,tsx}', 'apps/**/*.{ts,tsx}'],
    rules: {
      'import-x/no-restricted-paths': ['error', {
        zones: [
          {
            target: 'packages/schema/**/*',
            from: ['packages/core/**/*', 'packages/provider-github/**/*', 'packages/db/**/*', 'packages/models/**/*', 'packages/api/**/*', 'packages/ui/**/*', 'apps/worker/**/*', 'apps/dashboard/**/*']
          },
          {
            target: 'packages/core/**/*',
            from: ['packages/provider-github/**/*', 'packages/db/**/*', 'packages/models/**/*', 'packages/api/**/*', 'packages/ui/**/*', 'apps/worker/**/*', 'apps/dashboard/**/*']
          },
          {
            target: 'packages/db/**/*',
            from: ['packages/provider-github/**/*', 'packages/models/**/*', 'packages/api/**/*', 'packages/ui/**/*', 'apps/worker/**/*', 'apps/dashboard/**/*']
          },
          {
            target: 'packages/provider-github/**/*',
            from: ['packages/db/**/*', 'packages/models/**/*', 'packages/api/**/*', 'packages/ui/**/*', 'apps/worker/**/*', 'apps/dashboard/**/*']
          },
          {
            target: 'packages/models/**/*',
            from: ['packages/db/**/*', 'packages/provider-github/**/*', 'packages/api/**/*', 'packages/ui/**/*', 'apps/worker/**/*', 'apps/dashboard/**/*']
          },
          {
            target: 'packages/api/**/*',
            from: ['packages/ui/**/*', 'apps/worker/**/*', 'apps/dashboard/**/*']
          },
          {
            target: 'packages/ui/**/*',
            from: ['packages/core/**/*', 'packages/provider-github/**/*', 'packages/db/**/*', 'packages/models/**/*', 'packages/api/**/*', 'apps/worker/**/*', 'apps/dashboard/**/*']
          },
          {
            target: 'apps/dashboard/**/*',
            from: ['packages/core/**/*', 'packages/provider-github/**/*', 'packages/db/**/*', 'packages/models/**/*', 'packages/api/**/*', 'apps/worker/**/*']
          },
          {
            target: 'apps/worker/**/*',
            from: ['packages/ui/**/*', 'apps/dashboard/**/*']
          }
        ]
      }]
    }
  }
);
