import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import importX from 'eslint-plugin-import-x';
import reactHooks from 'eslint-plugin-react-hooks';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      // Recorded model responses and live re-run output: data, not source.
      'test/fixtures/**',
      'test/rerun/**',
      // Generated by `wrangler types`.
      'src/server/worker-env.d.ts',
      'worker-configuration.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx,js,mjs}'],
    plugins: { 'import-x': importX, 'react-hooks': reactHooks },
    settings: {
      // The resolver has to understand the @server/@client/@shared aliases from tsconfig, or every
      // internal import reads as unresolved and no-cycle/no-self-import are silently useless.
      'import-x/resolver-next': [
        createTypeScriptImportResolver({ project: './tsconfig.json' }),
      ],
    },
    rules: {
      // TypeScript resolves every identifier already, and does it correctly for types, `declare`,
      // and the Worker/DOM lib globals. Leaving this on means re-declaring hundreds of ambient
      // globals in ESLint just to get a worse version of a check `npm run typecheck` already runs.
      'no-undef': 'off',

      // The base rule cannot see TypeScript's type-only positions; the TS one can.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['error', {
        // `catch {}` is the preferred form, but an unused binding is not worth an error.
        caughtErrors: 'none',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      }],

      // `import-x/no-duplicates` and NOT the core `no-duplicate-imports`: the core rule is type-blind
      // and flags the deliberate `import { Hono }` + `import type { Context }` split as a duplicate.
      'import-x/no-duplicates': 'error',
      'import-x/no-self-import': 'error',
      'import-x/no-cycle': 'error',

      // An error, not a warning: the four places whose dependency array is deliberately narrower
      // than their closure now carry a line-level disable stating why. A new violation should fail.
      'react-hooks/exhaustive-deps': 'error',

      // Fires on the finding-title normalizer, which strips emoji and variation selectors from model
      // output. Those combining characters are the point of it, and its behaviour is pinned by tests.
      'no-misleading-character-class': 'off',

      // `any` is used deliberately at the provider and DB boundaries, where the shape is genuinely
      // unknown until it is parsed. Turning this on would mean ~100 suppressions, not better types.
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    files: ['src/client/**/*.{ts,tsx}'],
    rules: {
      'react-hooks/rules-of-hooks': 'error',
    },
  },

  {
    // Plain-JS scripts are not covered by tsconfig, so they need their globals declared.
    files: ['scripts/**/*.{js,mjs}'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        __dirname: 'readonly',
      },
    },
  },
);
