// Reports repo-wide comment density: comment lines / (comment + code) lines, blanks excluded.
//
// Repo-wide on purpose, never per-file. A handful of small modules are almost entirely commentary
// because they record an incident the code alone cannot explain (fingerprint.ts, models/limits.ts,
// review/budget.ts); a per-file threshold would force those to be diluted or the explanation
// deleted. The number that matters is the whole tree.
//
// A comment counts as the number of lines it WOULD take in `//` form at LINE_WIDTH, not the number
// of physical lines it occupies. Otherwise the metric is trivially gamed: reflowing a 6-line `//`
// block into one 600-character `/* ... */` deletes nothing and still shows a 5x improvement. Long
// `//` lines normalize the same way, so neither form is cheaper than the other.
//
// Usage:
//   node scripts/comment-density.mjs            # summary
//   node scripts/comment-density.mjs --top      # plus the 20 files with the most comment lines
//   node scripts/comment-density.mjs --max 5    # exit 1 above the given percentage (for CI)
import { readFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import path from 'node:path';

const ROOTS = ['src', 'test', 'scripts'];
const EXTS = new Set(['.ts', '.tsx', '.mjs', '.js']);
// Generated by `wrangler types`; not ours to edit.
const SKIP = new Set(['worker-env.d.ts', 'worker-configuration.d.ts']);

async function walk(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) await walk(full, out);
    else if (EXTS.has(path.extname(entry.name)) && !SKIP.has(entry.name)) out.push(full);
  }
  return out;
}

// Rendered width of a comment line in this repo: `//` comment lengths sit at 89/96/99/100 for
// p50/p75/p90/p95, so 100 is the line the codebase actually wraps to. CONTENT_WIDTH backs out the
// `// ` prefix.
const LINE_WIDTH = 100;
const CONTENT_WIDTH = LINE_WIDTH - 3;

// What this text would cost in `//` form: never fewer lines than it already occupies, and never
// fewer than its content needs at CONTENT_WIDTH.
function equivalentLines(contentChars, physicalLines) {
  return Math.max(physicalLines, Math.ceil(contentChars / CONTENT_WIDTH) || 1);
}

function countLines(file) {
  let comments = 0;
  let code = 0;
  let inBlock = false;
  let blockChars = 0;
  let blockPhysical = 0;

  const stripBlock = (line) => line
    .replace(/^\/\*+/, '')
    .replace(/\*+\/$/, '')
    .replace(/^\*+/, '')
    .trim();

  for (const raw of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;

    if (inBlock) {
      blockPhysical += 1;
      blockChars += stripBlock(line).length;
      if (line.includes('*/')) {
        inBlock = false;
        comments += equivalentLines(blockChars, blockPhysical);
      }
      continue;
    }
    if (line.startsWith('/*')) {
      blockPhysical = 1;
      blockChars = stripBlock(line).length;
      if (line.includes('*/')) {
        comments += equivalentLines(blockChars, blockPhysical);
      } else {
        inBlock = true;
      }
      continue;
    }
    if (line.startsWith('//')) {
      comments += equivalentLines(line.replace(/^\/+/, '').trim().length, 1);
      continue;
    }
    code += 1;
  }

  // An unterminated block (should not happen in valid source) still costs what it accumulated.
  if (inBlock) comments += equivalentLines(blockChars, blockPhysical);

  return { comments, code };
}

const files = (await Promise.all(ROOTS.map((root) => walk(root)))).flat();

let totalComments = 0;
let totalCode = 0;
const perFile = [];

for (const file of files) {
  const { comments, code } = countLines(file);
  totalComments += comments;
  totalCode += code;
  if (comments + code > 0) perFile.push({ file, comments, code });
}

const total = totalComments + totalCode;
const density = (100 * totalComments) / total;
console.log(`comment density: ${totalComments} / ${total} lines = ${density.toFixed(2)}%`);

if (process.argv.includes('--top')) {
  console.log('\nmost comment lines:');
  for (const entry of perFile.sort((a, b) => b.comments - a.comments).slice(0, 20)) {
    const pct = ((100 * entry.comments) / (entry.comments + entry.code)).toFixed(1);
    console.log(`  ${String(entry.comments).padStart(4)}c ${String(entry.code).padStart(5)}k ${pct.padStart(5)}%  ${entry.file}`);
  }
}

const maxIndex = process.argv.indexOf('--max');
if (maxIndex !== -1) {
  const limit = Number(process.argv[maxIndex + 1]);
  if (!Number.isFinite(limit)) {
    console.error('--max needs a number');
    process.exit(2);
  }
  if (density > limit) {
    console.error(`\nFAIL: ${density.toFixed(2)}% is above the ${limit}% ceiling.`);
    process.exit(1);
  }
  console.log(`OK: within the ${limit}% ceiling.`);
}
